### ISSUE TITLE
We should have an image (or og:image) for social media shares

### ISSUE THREAD

**Issue by PalleZingmark** [futurice/spiceprogram#126]
Would be nice to have a nice image, or even `og:image` and a Twitter card, for social media shares, there is none at the moment and I believe having one could draw some more attention to a share.

Currently on Facebook: 
![image](https://cloud.githubusercontent.com/assets/367036/21331007/a953f244-c640-11e6-866a-49ed5ea4d7d4.png)

Slack: 
![image](https://cloud.githubusercontent.com/assets/367036/21331032/c9d23c9c-c640-11e6-8815-aaaec77fb6f2.png)

**Comment by PalleZingmark** [comment]
Let me know if you want me to do a PR for this. 👍

**Comment by PalleZingmark** [comment]
Awesome @Wisheri! 👍

**Comment by vtainio** [comment]
It was all done by @anttiviljami ;)

**Comment by PalleZingmark** [comment]
Haha, ok. Equally awesomeness to @anttiviljami then. 😜
