### ISSUE TITLE
The page size could be a bit smaller

### ISSUE THREAD

**Issue by ttur** [futurice/spiceprogram#99]
The new version of the site is quite image heavy and some of the images are quite large. This results in 4.5MB page size. It'd be nice if we could shave a few megabytes off that and not contribute to the page bloat phenomenon :)

<img width="522" alt="filesizes" src="https://cloud.githubusercontent.com/assets/996293/20128763/480e22a0-a653-11e6-9272-633b440289c0.png">

**Comment by anttti** [comment]
I can take a look at this (given that I can get Ruby to stop vomiting)!

**Comment by anttti** [comment]
There you go: https://github.com/futurice/spiceprogram/pull/101
